### ISSUE TITLE
Graphic Slider- Large Practice Icon, placement and size

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com#10]
Practice icons should be larger and underlay the body copy and should be larger as in the comp:
![image](https://cloud.githubusercontent.com/assets/9142185/13472057/365a7bbe-e081-11e5-8fd9-f88c01b4fcfb.png)

Currently it is small and separated from all text:
![image](https://cloud.githubusercontent.com/assets/9142185/13472103/543f2eb8-e081-11e5-9722-8670c62a7ae5.png)

**Comment by mike3run** [comment]
Doing the icons larger would cause some alignment visual issues where an icon would cross to the next slide and so on…

The main problem I think is the icon of the group of people (3 people) since its wider that the rest limits the global styling of the icons on that size

**Comment by adam-s-p-** [comment]
What do you mean "cross to the next slide?"

**Comment by mike3run** [comment]
I mean a bit of the class-action icon would enter to the slide of product liability

**Comment by mike3run** [comment]
This issue has been handled on a previous pull request :)
