### ISSUE TITLE
Team Thumbnails- Roshawn Donahue Husband

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com#17]
Can "Roshawn Donahue" fit on one line as per the comp?
![image](https://cloud.githubusercontent.com/assets/9142185/13473600/06e8463e-e088-11e5-81c1-c4c940930a4d.png)

**Comment by mike3run** [comment]
Sure thing! My bad I measured the padding there based on Spencer Ryan's spacing :)

**Comment by adam-s-p-** [comment]
Thank you!
