### ISSUE TITLE
Homepage Layout- Padding

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com#19]
There should be more padding between the bottom of the Team Member section of the homepage and the news section of the Homepage:

![image](https://cloud.githubusercontent.com/assets/9142185/13473836/27ec6d50-e089-11e5-9c53-648992b11295.png)

In the comps we give about 260px of padding:
![image](https://cloud.githubusercontent.com/assets/9142185/13473845/34515ac4-e089-11e5-86bb-baf034cb5025.png)

**Comment by mike3run** [comment]
Done, it wasn't 260 but 130px :)
