### ISSUE TITLE
Icon Navigation- Selected Items

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com#22]
The selection atop the icon navigation in breakpoints 990px and below (and all other dropdowns) should be highlighted in gray as per the comps.
Currently, it is not highlighted:
![image](https://cloud.githubusercontent.com/assets/9142185/13474525/632feeca-e08c-11e5-84ec-2cd788ad3480.png)

It should look like this:
![image](https://cloud.githubusercontent.com/assets/9142185/13474561/90f9c7ae-e08c-11e5-8408-ef4a27a6db3d.png)

**Comment by mike3run** [comment]
Sorry my monitor didn't catch that slight gray color :)

**Comment by adam-s-p-** [comment]
No worries, Thanks!
